### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [T1rax/movies_auth_service#60]
Здравствуйте ! Хорошо поработали ! Есть несколько рекомендаций:

1. В документацию неплохо добавить ссылки по которым доступно АПИ и документация.
2. [Тут](https://github.com/T1rax/movies_auth_service/blob/b92207a78dbd6343c4e4aa4e001e6d00ffbf8c64/flask_app/Dockerfile#L13) используйте --no-cache-dir  (pip параметр) при создании образов Docker. Кэш обычно не нужен в образе Docker, и вы можете уменьшить размер образа, отключив кеш
3. [Тут](https://github.com/T1rax/movies_auth_service/blob/b92207a78dbd6343c4e4aa4e001e6d00ffbf8c64/flask_app/blueprints/basic_endpoints/__init__.py#L70) и по коду используйте https://docs.python.org/3/library/http.html#http.HTTPStatus, так код станет более читаемый.
4. На самом деле не очень хороший подход располагать код в `__init__.py` файлах, там обычно кладут импорты.
5. Код консольных команд https://github.com/T1rax/movies_auth_service/blob/b92207a78dbd6343c4e4aa4e001e6d00ffbf8c64/flask_app/blueprints/basic_endpoints/__init__.py#L80-L85 я бы посоветовал вынести в отдельный модуль.
6. Без версионирования API будет сложно перейти на новую версию, поэтому версионирование необходимо. Сделайте подобно как Вы уже делали /api/v1 структуру каталогов и путей. 
7. Не нашел у Вас АПИ управления ролями, вот эта часть где реализована ?
```
API для управления доступами
CRUD для управления ролями:
создание роли,
удаление роли,
изменение роли,
просмотр всех ролей.
назначить пользователю роль;
отобрать у пользователя роль;
метод для проверки наличия прав у пользователя.
```
Ведь где то же должна храниться связь пользователь - роли.
8. [Тут](https://github.com/T1rax/movies_auth_service/blob/b92207a78dbd6343c4e4aa4e001e6d00ffbf8c64/flask_app/database/models.py#L152) если в юзер агенте придет что то невообразимое -  DeviceDetector вызовет исключение. Поэтому для безопасности можно обернуть его в try-except.
9. [Тут](https://github.com/T1rax/movies_auth_service/blob/b92207a78dbd6343c4e4aa4e001e6d00ffbf8c64/flask_app/performance/tracing/tracer.py#L39-L40) лучше вынести в конфигурацию параметры подключения к егерю.
10. Давайте сделаем возможность через переменные окружения выключать трассировщик и лимитер.
11. [Тут](https://github.com/T1rax/movies_auth_service/blob/b92207a78dbd6343c4e4aa4e001e6d00ffbf8c64/flask_app/performance/tracing/tracer.py#L51) линтер ругается что не 4 пробела. Попробуйте https://black.readthedocs.io/en/stable/ и прогоните код, помогает легко соблюдать форматирование.
[Тут](https://github.com/T1rax/movies_auth_service/blob/b92207a78dbd6343c4e4aa4e001e6d00ffbf8c64/flask_app/tests/src/functional/test_get_user_description.py#L35) например 170 символов )
12. [Тут](https://github.com/T1rax/movies_auth_service/blob/b92207a78dbd6343c4e4aa4e001e6d00ffbf8c64/flask_app/routes/sign_in_history.py#L67) есть ли смысл возвращать значение True здесь ?
13. [Тут ](https://github.com/T1rax/movies_auth_service/blob/b92207a78dbd6343c4e4aa4e001e6d00ffbf8c64/flask_app/routes/social.py#L10) и вообще в коде хорошо бы пользоваться аннотациями типов и писать строки документации к методам.
14. [Тут](https://github.com/T1rax/movies_auth_service/blob/b92207a78dbd6343c4e4aa4e001e6d00ffbf8c64/flask_app/tests/fixtures/db.py#L15) просто хочу заметить, вы выбрали асинхронную модель, подменили редис, но вот запросы к БД postgresql останутся синхронными.
15. [Тут](https://github.com/T1rax/movies_auth_service/blob/b92207a78dbd6343c4e4aa4e001e6d00ffbf8c64/flask_app/blueprints/basic_endpoints/__init__.py#L50) вы использовали asynс, но в ручке ведь ничего не происходит асинхронного. Я бы не рекомендовал данный подход, так как такой код запускается в отдельном треде и изза накладных расходов скорее всего вы не получите какой то высокой производительности, а вот проблем добавиться может (инфраструктура Flask все таки синхронна). Я бы рекомендовал Вам использовать подход с gevent monkey_patch как у вас описано в теории.
16. При старте приложения не создаются партиции таблиц
<img width="308" alt="image" src="https://user-images.githubusercontent.com/73478414/235355589-4c30c1bd-37eb-4e99-89c4-7c50ce1f7c40.png">
посмотрите, код создания партиций должен присутствовать в миграциях.

**Comment by T1rax** [comment]
Первый готов

**Comment by BigDeepBlue** [comment]
Здравствуйте @T1rax @mod-web , отлично много поправили. Не нужно было выпиливать код по партицированию таблиц, ведь это одно из заданий спринта.
Смотрите, когда я писал о том что не создаются партиции - нужно было всего лишь создать миграцию которая эти таблицы бы создавала, у вас же был код тут https://github.com/T1rax/movies_auth_service/commit/4caa7e955d234fddd97dace76b5f72a1ca095b94  и в принципе он ведь норм, единственное нужно было заставить чтоб на чистой БД создавались эти партиции. (Можно просто написать отдельную например консольную команду которая бы при старте проверяла и создавала эти партиции)
